name: 'mnist'

batch_size: 128
num_workers: 8
data_dir: '.'
sample_shape: [256, 1, 28, 28]
fid_sample_shape: [500, 1, 28, 28]
n_dataset_samples: 50000
input_shape: [1, 28, 28]
plot_type: 'grid'
img_resolution: 28
in_channels: 1
out_channels: 1