defaults:
 - dataset: mnist
 - model: covae
 - network: autoencoder
use_logger: True
project: 'covae'
fast_dev_run: False
enable_progress_bar: False
root_dir: '.'
requeue: True
log_samples: True
compute_fid: True
log_rec: False
compute_rec_fid: False
seed: 42
extra_name: ''
reload: False
run_path: ''
log_model: 'all'
deterministic: False
sync_batchnorm: False

log_frequency: 10000
precision: 'bf16-mixed'
accumulate_grad_batches: 1
accelerator: 'auto'
strategy: 'auto'
devices: 'auto'
gradient_clip_val: 0
batch_multiplier: 1