name: 'covae_simple'

ema_rate: 0.9999
learning_rate: 1e-4
weight_decay: 0

step_schedule: 'exp'
sigma_min: 0.05
sigma_max: 3
rho: 7
start_scales: 2
end_scales: 256
total_training_steps: 400000
loss_mode: 'huber'
denoiser_loss_mode: 'l2'
use_gan: False
gan_warmup_steps: 0
gan_lambda: 1

kernel: 've'
p_mean: -1.1
p_std: 2.0
sigma_data: 0.5
norm_strength: 0.001
mid_t: 0.821
norm_weight: 'fixed'
noise_schedule: 'lognormal'

instance:
  _target_: models.covae_simple.CoVAESimple
  model:
    _target_: networks.autoencoder.AutoEncoder
    img_resolution: ${dataset.img_resolution}
    in_channels: ${dataset.in_channels}
    out_channels: ${dataset.out_channels}
    label_dim: 0
    model_channels: ${network.model_channels}
    channel_mult_enc: ${network.channel_mult_enc}
    num_blocks_enc: ${network.num_blocks_enc}
    channel_mult_dec: ${network.channel_mult_dec}
    num_blocks_dec: ${network.num_blocks_dec}
    attn_resolutions: ${network.attn_resolutions}
    dropout: ${network.dropout}
    z_channels: ${network.z_channels}
    final_dim: ${network.final_dim}
  step_schedule: ${model.step_schedule}
  sigma_min: ${model.sigma_min}
  sigma_max: ${model.sigma_max}
  rho: ${model.rho}
  start_scales: ${model.start_scales}
  end_scales: ${model.end_scales}
  total_training_steps: ${model.total_training_steps}
  noise_shape:
    _target_: models.factories.build_noise_shape
    img_resolution: ${dataset.img_resolution}
    channel_mult_enc: ${network.channel_mult_enc}
    z_channels: ${network.z_channels}
    final_dim: ${network.final_dim}
  loss_mode: ${model.loss_mode}
  denoiser_loss_mode: ${model.denoiser_loss_mode}
  use_gan: ${model.use_gan}
  gan_warmup_steps: ${model.gan_warmup_steps}
  discriminator:
    _target_: models.factories.build_discriminator
    enabled: ${model.use_gan}
    input_nc: ${dataset.in_channels}
    n_layers: 3
    use_actnorm: False
  gan_lambda: ${model.gan_lambda}
  kernel:
    _target_: models.factories.build_kernel
    name: ${model.kernel}
    sigma_min: ${model.sigma_min}
    sigma_max: ${model.sigma_max}
    sigma_data: ${model.sigma_data}
  p_mean: ${model.p_mean}
  p_std: ${model.p_std}
  sigma_data: ${model.sigma_data}
  norm_strength: ${model.norm_strength}
  mid_t: ${model.mid_t}
  norm_weight: ${model.norm_weight}
  noise_schedule: ${model.noise_schedule}
